name: flutter_news2021
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  google_fonts: 
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

  assets:
    - "assets/"

