name: flutter_news2021
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  foldable_sidebar: ^1.0.0
  cloud_firestore: ^1.0.7
  firebase_auth: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

  assets:
    - "assets/"

